name: typescript-check

on:
  pull_request:
    paths:
      - 'pkg/interface/**'

jobs:
  typescript-check:
    runs-on: ubuntu-latest
    name: "Check pkg/interface types"
    steps:
      - uses: actions/checkout@v2
      - run: cd 'pkg/interface' && npm i && npm run tsc
